# -*- coding: utf-8 -*-
"""Cópia de Proj_CIS-Imagens-Raio_X.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12k43AsfLLugGfjaCRurexy0HmzgadGsg

#Imports and Ajusting file
"""

pip install pydicom

import cv2
import pydicom
import pandas as pd
import os
import time
import math
import gdown
import zipfile
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from tqdm import tqdm

def download(id): 
    url = 'https://drive.google.com/uc?id=' + str(id)
    gdown.download(url, output = None, quiet = False)

def unzip(path): #Função para unzip
    zip = zipfile.ZipFile(path)
    zip.extractall()
    zip.close()

from google.colab import drive
drive.mount('/content/drive')

import glob 

i = glob.iglob("/train/**/*.dcm", recursive=True)

next(i)

from pydicom import dcmread
ds = dcmread(i)
print(ds.pixel_arra)

next(i)

import os, shutil

#move para o diretorio das fotos
os.chdir('/content/drive/MyDrive/RAIO-X/RAIO-X/archive.zip (Unzipped Files)')

if os.path.isdir("/train_all") is False:
os.makedirs("/train_all")

for c in glob.glob("/train/**/*.dicom", recursive=True) :
  shutil.move(c, "train_all")
  #shutil.copy(c, "train_all")

# https://drive.google.com/file/d/1ev-r31j8oRzDlKM_toaeADO2psrA_XXm/view?usp=sharing
download('1ev-r31j8oRzDlKM_toaeADO2psrA_XXm')
unzip('/content/archive.zip')

train_df = pd.read_csv('/content/train.csv')
test_df = pd.read_csv('/content/sample_submission.csv')

test_df.head(5)

train_df.head(5)

train_df

"""#Pre-processing"""

print("Columns:")
print(train_df.columns, "\n")

print("Types in columns:")
print(train_df.dtypes, "\n")

print("Types in info:")
print(train_df.describe(), "\n")

"""#The beginning"""

dictLabel = {0 : 'Abdomen' ,1 :'Ankle' ,2 :'Cervical Spine',3 : 'Chest' ,4 :'Clavicles' ,5 :'Elbow' ,6 :'Feet' ,
             7 : 'Finger' ,8 : 'Forearm' ,9 : 'Hand' ,10 : 'Hip' ,11 : 'Knee' ,12 : 'Lower Leg' ,13 : 'Lumbar Spine' ,
            14 : 'Others' ,15 :'Pelvis',16 :'Shoulder' ,17 :'Sinus' ,18 : 'Skull' ,19 : 'Thigh' ,20 :'Thoracic Spine',
             21: 'Wrist',}

dicom = pydicom.dcmread("/content/test/test/test/100/1.2.826.0.1.3680043.8.498.76021520764732566806005076288586953164/1.2.826.0.1.3680043.8.498.11778408564388558984021698740038761362/1.2.826.0.1.3680043.8.498.88649350262556129168764468888053917993-c.dcm")
img = dicom.pixel_array
plt.imshow(img, cmap = 'gray')
plt.show()

dicom = pydicom.dcmread("/content/test/test/test/1010/1.2.826.0.1.3680043.8.498.70879709419703008332654779724623905177/1.2.826.0.1.3680043.8.498.40346997148916954147067785194965187407/1.2.826.0.1.3680043.8.498.97605470189659234572021713783479421356-c.dcm")
img = dicom.pixel_array
plt.imshow(img, cmap = 'gray')
plt.show()

for i in train_df["SOPInstanceUID"][0:5]:
  path = "/content/train/"
  dicom = pydicom.dcmread(path + i)
  img = dicom.pixel_array
  plt.imshow(img, cmap = 'gray')
  plt.show()
  # print(i)

import os
os.walk("/content/train/")

path = "/content/train/"
filelist = []
for root, dirs, files in os.walk(path):
	for file in files:
        #append the file name to the list
		filelist.append(os.path.join(root,file))

#print all the file names
for name in filelist:
    print(name)

for filename in filelist:
    dicom = pydicom.dcmread(filename)
    img = dicom.pixel_array
    plt.imshow(img, cmap = 'gray')
    print ("\n" + filename)
    plt.show()

os.mkdir("/content/images/")

from PIL import Image
for filename in filelist:
    dicom = pydicom.dcmread(filename)
    img = dicom.pixel_array
    im = Image.fromarray(img)
    var = filename.split("/")
    patient = var[5]
    code = var[6]
    im.save("/content/images/" + code + ".tiff")